# GitHub Sponsors configuration
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors (primary)
github: [SoCkEt7]

# Buy Me a Coffee
# Update this username with the one you confirm at https://studio.buymeacoffee.com/dashboard
buy_me_a_coffee: SoCkEt7

