# GitHub Sponsors configuration
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors
github: [SoCkEt7]

# Buy Me a Coffee
buy_me_a_coffee: antoninnvh
custom: ["https://www.buymeacoffee.com/antoninnvh"]
